# -*- coding: utf-8 -*-
"""AdaptivePhishingDetection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xoZDwroOCDx-jPtrvMOSzP5r7kNnf3iP
"""

!pip install river

from google.colab import drive
drive.mount('/content/drive')

"""Balance QR Dataset"""

import pandas as pd

df_word = pd.read_csv("/content/drive/MyDrive/AdaptivePhishingDetection/Trap4PhishDataset/Word_Top10_Features.csv")
df_excel = pd.read_csv("/content/drive/MyDrive/AdaptivePhishingDetection/Trap4PhishDataset/Excel_Top10_Features.csv")
df_pdf = pd.read_csv("/content/drive/MyDrive/AdaptivePhishingDetection/Trap4PhishDataset/PDF_Top10_features.csv")
df_html = pd.read_csv("/content/drive/MyDrive/AdaptivePhishingDetection/Trap4PhishDataset/HTML_Top13_Features.csv")
df_qr_benign = pd.read_csv("/content/drive/MyDrive/AdaptivePhishingDetection/Trap4PhishDataset/qr_benign.csv")
df_qr_malicious = pd.read_csv("/content/drive/MyDrive/AdaptivePhishingDetection/Trap4PhishDataset/qr_malicious.csv")

import matplotlib.pyplot as plt

df_qr_benign["label"] = 0
df_qr_malicious["label"] = 1

datasets = {
    "Word": df_word,
    "Excel": df_excel,
    "PDF": df_pdf,
    "HTML": df_html,
    "QR_Benign": df_qr_benign,
    "QR_Malicious": df_qr_malicious
}


benign_counts = []
malicious_counts = []
names = []

for name, df in datasets.items():
    names.append(name)
    benign_counts.append((df["label"] == 0).sum())
    malicious_counts.append((df["label"] == 1).sum())

x = range(len(names))

plt.figure(figsize=(10,6))

plt.bar(x, benign_counts, label="Benign")
plt.bar(x, malicious_counts, bottom=benign_counts, label="Malicious")

plt.xticks(x, names)
plt.title("Dataset Class Distribution")
plt.xlabel("Dataset Type")
plt.ylabel("Data Count")
plt.legend()
plt.grid(axis="y", alpha=0.3)

plt.show()

df_word.head()

df_word.count()

df_excel.head()

df_excel.count()

df_pdf.head()

df_pdf.count()

df_html.head()

df_html.count()

df_qr_benign.head()

df_qr_benign.count()

df_qr_malicious.head()

df_qr_malicious.count()

"""Balance The Dataset"""

import pandas as pd

benign_df = pd.read_csv("/content/drive/MyDrive/AdaptivePhishingDetection/Trap4PhishDataset/qr_benign.csv")
malicious_df = pd.read_csv("/content/drive/MyDrive/AdaptivePhishingDetection/Trap4PhishDataset/qr_malicious.csv")

benign_sample = benign_df.sample(
    n=10000,
    random_state=42
)

malicious_sample = malicious_df.sample(
    n=10000,
    random_state=42
)

benign_sample["label"] = 0
malicious_sample["label"] = 1

qr_balanced = pd.concat(
    [benign_sample, malicious_sample],
    ignore_index=True
)

qr_balanced = qr_balanced.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

qr_balanced.to_csv(
    "/content/drive/MyDrive/AdaptivePhishingDetection/Trap4PhishDataset/qr_balanced.csv",
    index=False
)

df_qr = pd.read_csv("/content/drive/MyDrive/AdaptivePhishingDetection/Trap4PhishDataset/qr_balanced.csv")

df_qr.head()

df_qr.count()

import matplotlib.pyplot as plt

datasets = {
    "Word": df_word,
    "Excel": df_excel,
    "PDF": df_pdf,
    "HTML": df_html,
    "QR": df_qr
}

benign_counts = []
malicious_counts = []
names = []

for name, df in datasets.items():
    names.append(name)
    benign_counts.append((df["label"] == 0).sum())
    malicious_counts.append((df["label"] == 1).sum())

x = range(len(names))

plt.figure(figsize=(10,6))

plt.bar(x, benign_counts, label="Benign")
plt.bar(x, malicious_counts, bottom=benign_counts, label="Malicious")

plt.xticks(x, names)
plt.title("Dataset Class Distribution")
plt.xlabel("Dataset Type")
plt.ylabel("Data Count")
plt.legend()
plt.grid(axis="y", alpha=0.3)

plt.show()

"""QR Feature Extraction"""

import pandas as pd

def load_qr_dataset(qr_balanced):

    qr_df = pd.read_csv(qr_balanced)

    # keep only needed columns
    df = qr_df[["url", "label"]]

    return df

import re
import math
from urllib.parse import urlparse
from collections import Counter


# ----------------------------
# 1. ENTROPY
# ----------------------------
def entropy(text):
    if len(text) == 0:
        return 0

    probs = [c / len(text) for c in Counter(text).values()]
    return -sum(p * math.log2(p) for p in probs)


# ----------------------------
# 2. URL PARSING SAFELY
# ----------------------------
def safe_parse(url):
    try:
        url = str(url).strip()

        if url == "" or url.lower() == "nan":
            return urlparse("http://empty.local")

        # ensure scheme exists
        if not url.startswith(("http://", "https://")):
            url = "http://" + url

        # final safety parse
        return urlparse(url)

    except Exception:
        # fallback for ANY malformed URL (including IPv6 issues)
        return urlparse("http://invalid.local")


# ----------------------------
# 3. FEATURE EXTRACTOR
# ----------------------------
def extract_features(url):

    url = str(url).lower()
    parsed = safe_parse(url)

    return {
        # LENGTH
        "url_length": len(url),

        # ENTROPY (obfuscation)
        "entropy": entropy(url),

        # STRUCTURE
        "subdomain_count": parsed.netloc.count("."),
        "path_depth": parsed.path.count("/"),

        # NUMERIC PATTERNS
        "digit_ratio": sum(c.isdigit() for c in url) / (len(url) + 1),

        # SPECIAL CHARACTERS
        "special_char_ratio": len(re.findall(r"[^a-zA-Z0-9]", url)) / (len(url) + 1),

        # HOST ANOMALY
        "has_ip": int(bool(re.search(r"\d+\.\d+\.\d+\.\d+", url))),

        # PHISHING INTENT
        "keyword_score": sum(
            k in url for k in [
                "login", "verify", "secure", "account",
                "bank", "update", "password", "signin"
            ]
        )
    }

import pandas as pd


def build_dataset(df):

    X = []
    y = []

    invalid_urls = 0

    for _, row in df.iterrows():

        url = row["url"]
        label = row["label"]

        features = extract_features(url)

        # safety check
        if features["url_length"] == 0:
            invalid_urls += 1
            continue

        X.append(features)
        y.append(label)

    X = pd.DataFrame(X)

    print(f"[INFO] Invalid URLs skipped: {invalid_urls}")

    return X, y

def save_features(df, output_path):

    X, y = build_dataset(df)

    X["label"] = y

    X.to_csv(output_path, index=False)

    print(f"[INFO] Saved feature dataset → {output_path}")

save_features(load_qr_dataset("/content/drive/MyDrive/AdaptivePhishingDetection/Trap4PhishDataset/qr_balanced.csv"), "/content/drive/MyDrive/AdaptivePhishingDetection/Trap4PhishDataset/qr_features.csv")

df_qr_balanced = pd.read_csv("/content/drive/MyDrive/AdaptivePhishingDetection/Trap4PhishDataset/qr_features.csv")

df_qr_balanced.tail()

df_qr_balanced.count()

FEATURE_SCHEMA = [

    # =====================
    # GENERIC STATISTICAL FEATURES
    # =====================
    "file_size",
    "entropy",

    # =====================
    # STRUCTURAL FEATURES (ALL MODALITIES)
    # =====================
    "token_count",
    "special_char_ratio",
    "digit_ratio",
    "avg_token_length",

    # =====================
    # HTML / SCRIPT BEHAVIOR
    # =====================
    "tag_count",
    "script_count",
    "form_count",
    "external_link_count",

    # =====================
    # OFFICE BEHAVIOR
    # =====================
    "macro_present",
    "macro_keyword_score",

    # =====================
    # PDF STRUCTURE
    # =====================
    "pdf_stream_count",
    "pdf_metadata_size",

    # =====================
    # URL / QR FEATURES (CLEAN VERSION)
    # =====================
    "url_length",
    "subdomain_count",
    "path_depth",
    "has_ip",
    "keyword_score"
]

def to_unified(row, dataset_type):

    x = dict.fromkeys(FEATURE_SCHEMA, 0)

    # =====================
    # HTML
    # =====================
    if dataset_type == "html":

        x["entropy"] = row.get("entropy", 0)
        x["tag_count"] = row.get("tag_count", 0)
        x["form_count"] = row.get("form_count", 0)
        x["embedded_js_count"] = row.get("embedded_js_count", 0)
        x["external_link_count"] = row.get("external_link_count", 0)


    # =====================
    # WORD
    # =====================
    elif dataset_type == "word":

        x["entropy"] = row.get("entropy", 0)
        x["file_size"] = row.get("file_size", 0)

        x["macro_present"] = row.get("macro_present", 0)
        x["macro_keyword_score"] = row.get("vba_keywords_count", 0)


    # =====================
    # EXCEL
    # =====================
    elif dataset_type == "excel":

        x["entropy"] = row.get("entropy_of_text", 0)
        x["file_size"] = row.get("file_size", 0)

        x["macro_keyword_score"] = row.get("macro_token_count", 0)


    # =====================
    # PDF
    # =====================
    elif dataset_type == "pdf":

        x["entropy"] = row.get("entropy_of_streams", 0)
        x["file_size"] = row.get("file_size", 0)

        x["pdf_stream_count"] = row.get("stream_count", 0)
        x["pdf_metadata_size"] = row.get("metadata_size", 0)


    # =====================
    # QR (NOW USING PRECOMPUTED CSV)
    # =====================
    elif dataset_type == "qr":

        # DIRECT MAPPING FROM qr_features.csv
        x["url_length"] = row.get("url_length", 0)
        x["entropy"] = row.get("entropy", 0)

        x["subdomain_count"] = row.get("subdomain_count", 0)
        x["path_depth"] = row.get("path_depth", 0)

        x["digit_ratio"] = row.get("digit_ratio", 0)
        x["special_char_ratio"] = row.get("special_char_ratio", 0)

        x["has_ip"] = row.get("has_ip", 0)
        x["keyword_score"] = row.get("keyword_score", 0)


    return x

word_rows = df_word.to_dict("records")
excel_rows = df_excel.to_dict("records")
pdf_rows = df_pdf.to_dict("records")
html_rows = df_html.to_dict("records")
qr_rows = df_qr_balanced.to_dict("records")

word_stream = [
    (to_unified(r, "word"), r["label"], "word")
    for r in word_rows
]

excel_stream = [
    (to_unified(r, "excel"), r["label"], "excel")
    for r in excel_rows
]

pdf_stream = [
    (to_unified(r, "pdf"), r["label"], "pdf")
    for r in pdf_rows
]

html_stream = [
    (to_unified(r, "html"), r["label"], "html")
    for r in html_rows
]

qr_stream = [
    (to_unified(r, "qr"), r["label"], "qr")
    for r in qr_rows
]

import random

stream = word_stream + excel_stream + pdf_stream + html_stream + qr_stream
#random.shuffle(full_stream)

from river.forest import ARFClassifier
from river.tree import HoeffdingTreeClassifier, HoeffdingAdaptiveTreeClassifier
from river.linear_model import LogisticRegression
from river.drift import ADWIN, KSWIN, PageHinkley
from river import metrics

from river import metrics

def stream_evaluate(model, stream, drift_detector=None):

    word_end=20000
    excel_end=40000
    pdf_end=59296
    html_end=79293
    qr_end=99293

    acc = metrics.Accuracy()
    prec = metrics.Precision()
    rec = metrics.Recall()
    f1 = metrics.F1()

    accuracy_curve = []
    precision_curve = []
    recall_curve = []
    f1_curve = []

    drift_points = []

    stable_points = []
    sub_drift_points = []
    hard_drift_points = []
    extreme_drift_points = []

    for i, (x, y, dataset_type) in enumerate(stream):

        y_pred = model.predict_one(x)

        if y_pred is not None:

            acc.update(y, y_pred)
            prec.update(y, y_pred)
            rec.update(y, y_pred)
            f1.update(y, y_pred)


            # optional drift detector update
            if drift_detector is not None:
                error = int(y_pred != y)
                drift_detector.update(error)

                # -------------------------
                # DRIFT TYPE CLASSIFICATION
                # -------------------------
                if i < word_end:

                    drift_type = "STABLE"
                    stable_points.append(i)

                elif i < excel_end:

                    drift_type = "SUB DRIFT (Word → Excel)"
                    sub_drift_points.append(i)

                elif i < pdf_end:

                    drift_type = "SUB DRIFT (Excel → PDF)"
                    sub_drift_points.append(i)

                elif i < html_end:

                    drift_type = "HARD DRIFT (PDF → HTML)"
                    hard_drift_points.append(i)

                elif i < qr_end:

                    drift_type = "EXTREME DRIFT (HTML → QR)"
                    extreme_drift_points.append(i)

                if drift_detector.drift_detected:
                    drift_points.append({
                        "step": i,
                        "drift_type": drift_type,
                        "accuracy": acc.get(),
                        "f1": f1.get()
                    })

        model.learn_one(x, y)

        accuracy_curve.append(acc.get())
        precision_curve.append(prec.get())
        recall_curve.append(rec.get())
        f1_curve.append(f1.get())

    return {
        "accuracy": accuracy_curve,
        "precision": precision_curve,
        "recall": recall_curve,
        "f1": f1_curve,
        "drift_points": drift_points,
        "stable_points": stable_points,
        "sub_drift_points": sub_drift_points,
        "hard_drift_points": hard_drift_points,
        "extreme_drift_points": extreme_drift_points
    }

print(len(stream))

"""# Models"""

lr = LogisticRegression()

arf = ARFClassifier(seed=42)

ht = HoeffdingTreeClassifier()

hat = HoeffdingAdaptiveTreeClassifier()

adwin = ADWIN()

kswin = KSWIN(alpha=0.001)

ph = PageHinkley()

lr_results = stream_evaluate(
    lr,
    stream,
    drift_detector=None
)

arf = ARFClassifier(seed=42)

arf_adwin_results = stream_evaluate(
    arf,
    stream,
    drift_detector=adwin
)

arf_kswin_results= stream_evaluate(
    arf,
    stream,
    drift_detector=kswin
)

arf_ph_results = stream_evaluate(
    arf,
    stream,
    drift_detector=ph
)

ht_adwin_results = stream_evaluate(
    ht,
    stream,
    drift_detector=adwin
)

ht_kswin_results = stream_evaluate(
    ht,
    stream,
    drift_detector=kswin
)

ht_ph_results = stream_evaluate(
    ht,
    stream,
    drift_detector=ph
)

hat_adwin_results = stream_evaluate(
    hat,
    stream,
    drift_detector=adwin
)

hat_kswin_results = stream_evaluate(
    hat,
    stream,
    drift_detector=kswin
)

hat_ph_results = stream_evaluate(
    hat,
    stream,
    drift_detector=ph
)

import matplotlib.pyplot as plt

plt.figure(figsize=(10,5))

plt.plot(lr_results["accuracy"], label="LR")
plt.plot(arf_adwin_results["accuracy"], label="ARF-ADWIN")
plt.plot(arf_kswin_results["accuracy"], label="ARF-KSWIN")
plt.plot(arf_ph_results["accuracy"], label="ARF-Page Hinkley")
plt.plot(ht_adwin_results["accuracy"], label="HT-ADWIN")
plt.plot(ht_kswin_results["accuracy"], label="HT-KSWIN")
plt.plot(ht_ph_results["accuracy"], label="HT-Page Hinkley")
plt.plot(hat_adwin_results["accuracy"], label="HAT-ADWIN")
plt.plot(hat_kswin_results["accuracy"], label="ARF-KSWIN")
plt.plot(hat_ph_results["accuracy"], label="HAT-Page Hinkley")

plt.title("Accuracy Under Concept Drift")
plt.legend()
plt.show()

import matplotlib.pyplot as plt

plt.figure(figsize=(10,5))

plt.plot(lr_results["f1"], label="LR")
plt.plot(arf_adwin_results["f1"], label="ARF-ADWIN")
plt.plot(arf_kswin_results["f1"], label="ARF-KSWIN")
plt.plot(arf_ph_results["f1"], label="ARF-Page Hinkley")
plt.plot(ht_adwin_results["f1"], label="HT-ADWIN")
plt.plot(ht_kswin_results["f1"], label="HT-KSWIN")
plt.plot(ht_ph_results["f1"], label="HT-Page Hinkley")
plt.plot(hat_adwin_results["f1"], label="HAT-ADWIN")
plt.plot(hat_kswin_results["f1"], label="ARF-KSWIN")
plt.plot(hat_ph_results["f1"], label="HAT-Page Hinkley")

plt.title("F1 -Score Under Concept Drift")
plt.legend()
plt.show()

plt.figure(figsize=(12,6))

# Baseline
plt.plot(lr_results["accuracy"], label="Logistic Regression", linewidth=2)

# Adaptive models
plt.plot(arf_adwin_results["accuracy"], label="ARF")
plt.plot(ht_adwin_results["accuracy"], label="Hoeffding Tree")
plt.plot(hat_adwin_results["accuracy"], label="Hoeffding Adaptive Tree")

plt.title("Baseline vs Adaptive Models (Accuracy with ADWIN Drift Detector)")
plt.xlabel("Time Step")
plt.ylabel("Accuracy")
plt.grid(True, alpha=0.3)
plt.legend()
plt.show()

import matplotlib.pyplot as plt

plt.figure(figsize=(12,6))

# Baseline
plt.plot(lr_results["f1"], label="Logistic Regression", linewidth=2)

# Adaptive models
plt.plot(arf_adwin_results["f1"], label="ARF")
plt.plot(ht_adwin_results["f1"], label="Hoeffding Tree")
plt.plot(hat_adwin_results["f1"], label="Hoeffding Adaptive Tree")

plt.title("Baseline vs Adaptive Models (F1 - Score Under Drift)")
plt.xlabel("Time Step")
plt.ylabel("F1 - Score")
plt.grid(True, alpha=0.3)
plt.legend()
plt.show()

plt.plot(lr_results["precision"], label="Precision")
plt.plot(lr_results["recall"], label="Recall")

plt.title("Precision vs Recall (Logistic Regression)")
plt.legend()
plt.show()

plt.plot(arf_adwin_results["precision"], label="Precision_ARF_ADWIN")
plt.plot(arf_adwin_results["recall"], label="Recall_ARF_ADWIN")

plt.plot(arf_ph_results["precision"], label="Precision_ARF_PH")
plt.plot(arf_ph_results["recall"], label="Recall_PH")

plt.title("Precision vs Recall (ARF-ADWIN vs ARF-PH)")
plt.legend()
plt.show()

plt.figure(figsize=(12,6))

plt.plot(arf_adwin_results["accuracy"], label="ARF + ADWIN", linewidth=2)
plt.plot(arf_kswin_results["accuracy"], label="ARF + KSWIN")
plt.plot(arf_ph_results["accuracy"], label="ARF + Page-Hinkley")

plt.title("Effect of Drift Detectors on ARF Performance")
plt.xlabel("Zaman")
plt.ylabel("Accuracy")
plt.grid(True, alpha=0.3)
plt.legend()
plt.show()

plt.figure(figsize=(12,6))

plt.plot(arf_adwin_results["f1"], label="ARF + ADWIN", linewidth=2)
plt.plot(arf_kswin_results["f1"], label="ARF + KSWIN")
plt.plot(arf_ph_results["f1"], label="ARF + Page-Hinkley")

plt.title("Effect of Drift Detectors on ARF Performance")
plt.xlabel("Time Step")
plt.ylabel("F1 - Score")
plt.grid(True, alpha=0.3)
plt.legend()
plt.show()

"""RF To Reveal Noise In Datasets Analysis"""

import pandas as pd
import numpy as np

def analyze_label_noise(model, X, y, dataset_type=None):

    results = []

    predictions = model.predict(X)

    for i in range(len(X)):

        true_label = y.iloc[i] if hasattr(y, "iloc") else y[i]
        pred_label = predictions[i]

        results.append({
            "true_label": true_label,
            "pred_label": pred_label,
            "is_noisy": int(true_label != pred_label),
            "dataset_type": dataset_type
        })

    df = pd.DataFrame(results)

    return df

def noise_summary(df):

    total = len(df)
    noisy = df["is_noisy"].sum()

    print("Total samples:", total)
    print("Noisy samples:", noisy)
    print("Noise ratio:", noisy / total)

    return {
        "total": total,
        "noisy": noisy,
        "noise_ratio": noisy / total
    }

def classwise_noise(df):

    summary = df.groupby("true_label")["is_noisy"].mean()

    print("\nClass-wise noise rate:")
    print(summary)

    return summary

def modality_noise(df):

    summary = df.groupby("dataset_type")["is_noisy"].mean()

    print("\nModality-wise noise rate:")
    print(summary)

    return summary

import matplotlib.pyplot as plt

def plot_noise(modality_summary):

    modality_summary.plot(kind="bar")

    plt.title("Label Noise by Modality")
    plt.ylabel("Noise Ratio")
    plt.xlabel("Dataset Type")

    plt.show()

df_results = analyze_label_noise(rf, X_test, y_test, dataset_type="qr")

summary = noise_summary(df_results)
classwise = classwise_noise(df_results)
modality = modality_noise(df_results)

plot_noise(modality)